# Generated by Django 3.0.6 on 2020-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactors',
            name='group',
            field=models.CharField(choices=[('Directors', 'Directors'), ('Actors', 'Actors'), ('Crew', 'Crew'), ('Photographers', 'Photographers'), ('Post Production', 'Post Production'), ('Production', 'Production'), ('Makeup Artist', 'Makeup Artist'), ('Dancers', 'Dancers'), ('Writers', 'Writers')], default='none', max_length=50, null=True),
        ),
    ]
