# Generated by Django 3.0.6 on 2021-01-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0003_reel_writingsamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsamples',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='uploads/'),
        ),
    ]
