# Generated by Django 3.0.6 on 2021-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0004_writingsamples_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlistings',
            name='genre',
            field=models.CharField(choices=[('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Experimental', 'Experimental'), ('Feature', 'Feature'), ('Music Video', 'Music Video'), ('Short', 'Short'), ('Student', 'Student'), ('Television', 'Television'), ('Virtual Reality', 'Virtual Reality'), ('Web/New Media', 'Web/New Media'), ('Theater', 'Theater')], default='null', max_length=40),
        ),
    ]
