# Generated by Django 3.0.6 on 2021-01-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0005_auto_20210119_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='reels',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
