# Generated by Django 3.0.6 on 2021-01-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0006_auto_20210127_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reel',
            old_name='reels',
            new_name='reelURL',
        ),
    ]
