# Generated by Django 3.0.6 on 2021-02-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0007_auto_20210127_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='Reel_Link',
        ),
        migrations.RemoveField(
            model_name='actors',
            name='Writing_Samples',
        ),
        migrations.AddField(
            model_name='actors',
            name='linkedIn',
            field=models.TextField(default='no url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actors',
            name='post_production_roles',
            field=models.TextField(default='no url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actors',
            name='production_roles',
            field=models.TextField(default='no url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actors',
            name='project_types',
            field=models.TextField(default='no url', max_length=200),
        ),
        migrations.AddField(
            model_name='actors',
            name='writing_genres',
            field=models.TextField(default='no url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actors',
            name='youtube_or_vimeo',
            field=models.TextField(default='no url', max_length=300, null=True),
        ),
    ]
