# Generated by Django 3.0.6 on 2021-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0010_auto_20210210_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='open_crew_positions',
            new_name='crew_positions',
        ),
        migrations.AddField(
            model_name='listings',
            name='post_production_positions',
            field=models.TextField(default='', max_length=300),
        ),
    ]
