# Generated by Django 3.0.6 on 2021-02-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0012_auto_20210215_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlistings',
            name='genre',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
