# Generated by Django 3.0.6 on 2021-02-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0014_auto_20210215_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='crew_positions',
            field=models.TextField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='post_production_positions',
            field=models.TextField(default='', max_length=300, null=True),
        ),
    ]
