# Generated by Django 3.0.6 on 2021-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0019_auto_20210311_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='reelURL',
        ),
        migrations.AddField(
            model_name='reel',
            name='samples',
            field=models.FileField(default='', null=True, upload_to='uploads/'),
        ),
    ]
