# Generated by Django 3.0.6 on 2021-03-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0020_auto_20210315_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reel',
            old_name='samples',
            new_name='reel',
        ),
    ]
