# Generated by Django 3.0.6 on 2021-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0021_auto_20210315_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_applications',
            name='date_submitted',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_applications',
            name='listing_thumbnail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_applications',
            name='listing_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
