# Generated by Django 3.0.6 on 2021-03-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0023_acceptedroles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedroles',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='acceptedroles',
            name='lastname',
        ),
    ]
