# Generated by Django 3.0.6 on 2021-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0027_auto_20210325_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroles',
            name='role_thumbnail',
            field=models.ImageField(default='///', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='director_email',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
