# Generated by Django 3.0.6 on 2021-03-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0028_auto_20210328_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedroles',
            name='public_id_of_listing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DeclinedRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('profile_picture', models.CharField(max_length=255, null=True)),
                ('public_id_of_listing', models.CharField(max_length=255, null=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunday.Listings')),
            ],
        ),
    ]
