# Generated by Django 3.0.6 on 2021-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0029_auto_20210328_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroles',
            name='role_status',
            field=models.CharField(default='Open', max_length=100, null=True),
        ),
    ]
