# Generated by Django 3.0.6 on 2021-03-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0030_filmroles_role_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroles',
            name='listing_public_id',
            field=models.CharField(default='Open', max_length=200, null=True),
        ),
    ]
