# Generated by Django 3.0.6 on 2021-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0031_filmroles_listing_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_applications',
            name='profile_picture',
            field=models.ImageField(default='///', upload_to='images/'),
        ),
    ]
