# Generated by Django 3.0.6 on 2021-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0033_auto_20210401_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_applications',
            name='status',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
    ]
