# Generated by Django 3.0.6 on 2021-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0034_auto_20210405_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroles',
            name='role_type',
            field=models.CharField(default='Did not enter a role type', max_length=100, null=True),
        ),
    ]
