# Generated by Django 3.0.6 on 2021-04-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0037_listings_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='languages_spoken',
            field=models.TextField(default='no url', max_length=1000, null=True),
        ),
    ]
