# Generated by Django 3.0.6 on 2021-04-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0039_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmroles',
            name='role_thumbnail',
            field=models.TextField(default='', null=True),
        ),
    ]
