# Generated by Django 3.0.6 on 2021-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0040_auto_20210420_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
