# Generated by Django 3.0.6 on 2021-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0041_thumbnails_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnails',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
