# Generated by Django 3.0.6 on 2021-04-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0042_auto_20210421_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnails',
            name='thumbnail',
            field=models.ImageField(default='///', max_length=300, upload_to='images/'),
        ),
    ]
