# Generated by Django 3.0.6 on 2021-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0045_auto_20210428_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='poster',
            field=models.ImageField(default='///', null=True, upload_to='images/'),
        ),
    ]
