# Generated by Django 3.0.6 on 2021-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0047_auto_20210502_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlistings',
            name='random_public_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
