# Generated by Django 3.0.6 on 2021-06-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0049_auto_20210529_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroles',
            name='character_name',
            field=models.CharField(default='Did not enter a Name', max_length=100, null=True),
        ),
    ]
