# Generated by Django 3.0.6 on 2021-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0050_auto_20210604_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='date_joined',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
