# Generated by Django 3.0.6 on 2021-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0050_filmroles_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='director_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
