# Generated by Django 3.0.6 on 2021-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0051_listings_director_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='location',
            new_name='state_location',
        ),
        migrations.AddField(
            model_name='listings',
            name='city_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
