# Generated by Django 3.0.6 on 2021-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0052_auto_20210605_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='title',
            field=models.TextField(default='no url', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='year_created',
            field=models.TextField(default='no url', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='title',
            field=models.TextField(default='no url', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='year_created',
            field=models.TextField(default='no url', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='writingsamples',
            name='title',
            field=models.TextField(default='no url', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='writingsamples',
            name='year_created',
            field=models.TextField(default='no url', max_length=250, null=True),
        ),
    ]
