# Generated by Django 3.0.6 on 2021-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0053_auto_20210607_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='twitter',
            field=models.TextField(default='no url', max_length=300, null=True),
        ),
    ]
