# Generated by Django 3.0.6 on 2021-06-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0054_actors_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='twitter',
            field=models.TextField(default='', max_length=300, null=True),
        ),
    ]
