# Generated by Django 3.0.6 on 2021-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0055_auto_20210607_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='city_location',
            field=models.CharField(default='Where are you based?', max_length=50, null=True),
        ),
    ]
