# Generated by Django 3.0.6 on 2021-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0056_actors_city_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='reel',
            field=models.FileField(default='', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='actors',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='uploads/'),
        ),
    ]
