# Generated by Django 3.0.6 on 2021-06-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0057_auto_20210610_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='thumbnail',
            new_name='ree_thumbnail',
        ),
    ]
