# Generated by Django 3.0.6 on 2021-06-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0058_auto_20210610_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='ree_thumbnail',
            new_name='reel_thumbnail',
        ),
    ]
