# Generated by Django 3.0.6 on 2021-06-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0060_crewcards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewcards',
            old_name='description',
            new_name='card_description',
        ),
    ]
