# Generated by Django 3.0.6 on 2021-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0061_auto_20210610_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='paid_listing',
            field=models.CharField(default=False, max_length=6, null=True),
        ),
    ]
