# Generated by Django 3.0.6 on 2021-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0062_actors_paid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='city_location',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='location',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='overview',
            field=models.TextField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='studio',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.TextField(default='', max_length=300, null=True),
        ),
    ]
