# Generated by Django 3.0.6 on 2021-06-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0063_auto_20210620_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='return_to_page',
            field=models.CharField(default=False, max_length=6, null=True),
        ),
    ]
