# Generated by Django 3.0.6 on 2021-06-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0064_actors_return_to_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='group',
            field=models.CharField(choices=[('Directors/Producers', 'Directors'), ('Actors', 'Actors'), ('Crew', 'Crew'), ('Photographers', 'Photographers'), ('Post Production', 'Post Production'), ('Production', 'Production'), ('Makeup Artist', 'Makeup Artist'), ('Dancers', 'Dancers'), ('Writers', 'Writers')], default='none', max_length=50, null=True),
        ),
    ]
