# Generated by Django 3.0.6 on 2021-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0065_auto_20210622_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='hasArt',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasCamera',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasHMU',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasLighting',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasSound',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
