# Generated by Django 3.0.6 on 2021-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0066_auto_20210623_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProductionRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Did not enter a Name', max_length=100, null=True)),
                ('tag', models.CharField(default='', max_length=10, null=True)),
                ('listing_public_id', models.CharField(default='Open', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Did not enter a Name', max_length=100, null=True)),
                ('tag', models.CharField(default='', max_length=10, null=True)),
                ('listing_public_id', models.CharField(default='Open', max_length=200, null=True)),
            ],
        ),
    ]
