# Generated by Django 3.0.6 on 2021-06-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0067_postproductionroles_productionroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='hasAnimator',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasColor',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasEditor',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='listings',
            name='hasVFX',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
