# Generated by Django 3.0.6 on 2021-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0068_auto_20210624_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionroles',
            name='role_status',
            field=models.CharField(default='Open', max_length=10, null=True),
        ),
    ]
