# Generated by Django 3.0.6 on 2021-06-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0070_postproductionroles_role_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='group',
            field=models.CharField(choices=[('Directors/Producers', 'Directors'), ('Actors', 'Actors'), ('Photographers', 'Photographers'), ('HMU', 'HMU'), ('Art', 'Art'), ('Camer', 'Camer'), ('Lighting', 'Lighting'), ('Sound', 'Sound'), ('Editor', 'Editor'), ('VFX', 'VFX'), ('Animator', 'Animator'), ('Dancers', 'Dancers'), ('Writers', 'Writers')], default='none', max_length=50, null=True),
        ),
    ]
